"""Unified the date and time fields

Revision ID: 41c1bcbcd784
Revises: efb40ca586f1
Create Date: 2025-04-24 19:33:12.484021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41c1bcbcd784'
down_revision: Union[str, None] = 'efb40ca586f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_schedule', sa.Column('scheduled_at', sa.DateTime(), nullable=False))
    op.drop_column('lesson_schedule', 'time')
    op.drop_column('lesson_schedule', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_schedule', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('lesson_schedule', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('lesson_schedule', 'scheduled_at')
    # ### end Alembic commands ###
