"""Company id can be nulled

Revision ID: aaaaaf899c2e
Revises: bb8e7eec28c5
Create Date: 2025-04-23 19:32:22.608433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaaaf899c2e'
down_revision: Union[str, None] = 'bb8e7eec28c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_schedule', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lessons', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lessons', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lesson_schedule', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
