"""added student attendance

Revision ID: cfcb13ec1a3a
Revises: 3a502f15cad3
Create Date: 2025-06-22 01:26:03.125605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcb13ec1a3a'
down_revision: Union[str, None] = '3a502f15cad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_schedule_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['lesson_schedule.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_schedule_attendance_id'), 'lesson_schedule_attendance', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_schedule_attendance_id'), table_name='lesson_schedule_attendance')
    op.drop_table('lesson_schedule_attendance')
    # ### end Alembic commands ###
