"""Added minutes duration on the lesson schedule

Revision ID: efb40ca586f1
Revises: 6f3bf2a09547
Create Date: 2025-04-24 19:24:38.013452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb40ca586f1'
down_revision: Union[str, None] = '6f3bf2a09547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_schedule', sa.Column('minutes_duration', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_schedule', 'minutes_duration')
    # ### end Alembic commands ###
